### ISSUE TITLE
[bug] - MathText rendering upside down.

### ISSUE THREAD

**Issue by niklebedenko** [imaphatduc/cubecubed#11]
**Describe the bug**
`MathText` objects render upside down.

**To Reproduce**
Run the code in [the `texvector.js` example](https://github.com/imaphatduc/cubecubed/blob/master/examples/texvector.js) on Windows, after initialising a new workspace with `npx ccw <name>` with `vite` enabled.

I've also experienced this in other scenes I made myself.

**Your browser**
Reproduced on Chrome, Edge. This is may be an OS-dependent error.

**Can you make a guess?**
The [`MathTex` cubicon](https://github.com/imaphatduc/cubecubed/blob/master/src/svg/cubicons/MathText.ts), I suppose?

**Expected behavior**
It should be the correct way up.

**Screenshots**
![image](https://user-images.githubusercontent.com/98320255/167200956-c98aa3ba-ba72-4241-b520-9bf391e835f2.png)

**Comment by imaphatduc** [comment]
Okay, I've tested it in Chrome (Edge) and Firefox. This problem happens because of the Chrome's conflicts when apply multiple SVG transform actions at a time (i.e. translate, rotate). It should work as expected in Firefox. I'll work on this issue asap.

Thank you for reporting it!

**Comment by imaphatduc** [comment]
This should be fixed in the recent commit ([8ab241f](https://github.com/imaphatduc/cubecubed/commit/8ab241fb4228c96626a7a9049266c4fc513071cf)) with detail description. I'll close this issue now.
