### ISSUE TITLE
'CreatePlaneShape' is not exported by index.ts, but is used by example.js

### ISSUE THREAD

**Issue by kaptsanovb** [imaphatduc/cubecubed#14]
**Describe the bug**
example.js uses 'CreatePlaneShape', while it's not being exported by index.ts.

**To Reproduce**
I set up the CCW (npx ccw) and ran the dev server (npm run dev), then in the browser console there is an error.

**Your browser**
Chrome.

**Can you make a guess?**
'CreateShape' is exported by index.ts, so maybe that's the correct function? It worked after I changed all mentions of 'CreatePlaneShape' to 'CreateShape' 

**Expected behavior**
The example page showing an example.

**Comment by imaphatduc** [comment]
Fixed in the latest commit. Thanks for notify me of this (and `example.js` is even the project frontpage :))
