### ISSUE TITLE
Animations broke

### ISSUE THREAD

**Issue by marvin-j97** [imaphatduc/cubecubed#3]
Animations broke

Graphing example @ 43f63ee
![anim1](https://user-images.githubusercontent.com/33938500/147955600-ebbc3041-5a85-4e85-b9eb-aa97a5b07a97.gif)

Graphing example @ 9a655a6 (same for d345806)
![anim2](https://user-images.githubusercontent.com/33938500/147955623-fb37f37b-81c6-4af7-94e6-3cc03cf43b29.gif)

Console:
![bug](https://user-images.githubusercontent.com/33938500/147955647-addcf66a-991d-4d90-ad7e-296b90e6db3c.png)

**Comment by imaphatduc** [comment]
This [commit](https://github.com/imaphatduc/cubecubed/commit/d559de15d747b8004d14e93c423fe170fe586710) fixed the bug.
