### ISSUE TITLE
Cannot Translate, Rotate vectors

### ISSUE THREAD

**Issue by marvin-j97** [imaphatduc/cubecubed#7]
```typescript
const v1 = new Vector({
    group: vectors,
    endPoint: new Vector2(3, 2),
    CONFIG: {
      lineColor: COLOR.TEAL_1,
    }
  });

  const v2 = new Vector({
    group: vectors,
    startPoint: new Vector2(0, 0,),
    endPoint: new Vector2(-1, 2),
    CONFIG: {
      lineColor: COLOR.RED_1,
    }
  });

vectors.play([new Create({ cubicon: v1 })]);
vectors.play([new Create({ cubicon: v2 })]);

vectors.play([
    new Translate({
      cubicon: v2,
      vector: v1.endPoint,
    })
  ])
```

Changing src/animations/translate.ts:39 from `cubicon.svgWrapper` to `cubicon.stroke` fixes it but isn't really a fix.
Same for Rotate

### Expected result

![lincomb](https://user-images.githubusercontent.com/33938500/148295172-33446ebb-b764-401d-bfe3-d1b87e88c75f.gif)

**Comment by imaphatduc** [comment]
This bug is because I've implemented `svgWrapper` for Rectangle (and Square) and not the other cubicons (Vector in this situation). I'll add the feature as soon as possible and will notify you when I finish it.

**Comment by imaphatduc** [comment]
I fixed this bug. Thanks!
